### ISSUE TITLE
Pressing return/enter on the postcode input box doesn't perform a search

### ISSUE THREAD

**Issue by Kriskit** [coders-for-labour/dashboard-for-labour#2]
When entering your postcode into the constituency finder, if you press return/enter I think it should perform a search.

**Comment by chrisbateskeegan** [comment]
This is actually more tricky to fix than it might seem. The paper-button element doesn't extend the native button element and the form <enter> behaviour requires a native button to behave this way. 

This requires some further experimentation but as it's not a blocker I'll leave it for now.

**Comment by Kriskit** [comment]
Can you not capture the key presses on the input itself?

My Polymer knowledge is lacking unfortunately.

**Comment by TomCahill** [comment]
https://github.com/coders-for-labour/dashboard-for-labour/commit/e0fbcdb65db92e9f8d1a8a40eb48d7bab9b590fb - 2 Years too late?
