### ISSUE TITLE
Constituency search input is illegible

### ISSUE THREAD

**Issue by Kriskit** [coders-for-labour/dashboard-for-labour#3]
The colours make it very difficult to read what you're typing as well as the placeholder.
![image](https://cloud.githubusercontent.com/assets/1172054/26395248/677df648-4067-11e7-8bf6-aab2178bfb67.png)

**Comment by Kriskit** [comment]
![image](https://cloud.githubusercontent.com/assets/1172054/26395276/77315bac-4067-11e7-9390-d34f435a4a10.png)

**Comment by chrisbateskeegan** [comment]
Fixed in v1.0.1
