### ISSUE TITLE
Twibbyn: Selecting a campaign could be more obvious

### ISSUE THREAD

**Issue by Kriskit** [coders-for-labour/dashboard-for-labour#4]
I think campaign selection could be a bit more obvious, having to hover over it and then click a very small icon seems unnecessary. A click on the whole campaign item seems more appropriate.

![image](https://cloud.githubusercontent.com/assets/1172054/26395441/de74d064-4067-11e7-803e-068c46b2ce36.png)

**Comment by chrisbateskeegan** [comment]
Fixed in v1.0.1
