### ISSUE TITLE
Avatar doesn't display if changed in Twitter after first dashboard login

### ISSUE THREAD

**Issue by Kriskit** [coders-for-labour/dashboard-for-labour#5]
I believe you are aware of this issue already, but good to get it added in here :)

![image](https://cloud.githubusercontent.com/assets/1172054/26395505/16711388-4068-11e7-9773-24bd236cb566.png)

**Comment by chrisbateskeegan** [comment]
Fixed (to a certain extent) in v1.0.2. Logging in will refresh the app info (including profile urls).
