### ISSUE TITLE
Missing images on Twibbyn select screen

### ISSUE THREAD

**Issue by TomFromThePool** [coders-for-labour/dashboard-for-labour#6]
Some of the images appear to be missing on the Twibbyn selection screen.
![missing images](https://cloud.githubusercontent.com/assets/998527/26396082/02650a28-406a-11e7-8182-dfbe754c293d.PNG)

**Comment by Kriskit** [comment]
Related? https://github.com/coders-for-labour/dashboard-for-labour/issues/5

**Comment by chrisbateskeegan** [comment]
Yes, this is the same as issue #5.
