### ISSUE TITLE
Integrate Buttress

### ISSUE THREAD

**Issue by chrisbateskeegan** [coders-for-labour/dashboard-for-labour#9]
The original D4L app was built using Rhizome, but that is no longer being actively worked on. Buttress was forked from Rhizome in early 2018 and is now the primary focus of development effort.

**Comment by TomCahill** [comment]
This work has now been completed as part of the feature/working-state branch, this branch has now been closed off and merged into develop.

Buttress has now fully replaced Rhizome and is integrated with the application. Basic schema's have been setup although these will need more work.
